### ISSUE TITLE
Failed when sssd is not installed

### ISSUE THREAD

**Issue by jpmahowald** [RedHatOfficial/ansible-role-rhel7-stig#11]
#### Description of problem:

Role fails when sssd is not installed.

#### SCAP Security Guide Version:

ansible-rhel7-disa-stig-role on master branch at  ba92999e77e46224e7eeb1fc48a0473bade79d82

#### Operating System Version:

CentOS 7

#### Steps to Reproduce:

1. Create a Google Compute Platform  instance  using   --image=centos-7-v20190312 --image-project=centos-cloud 
2. ansible-playbook  test/test.yml

#### Actual Results:

```
TASK [ansible-rhel7-disa-stig-role : Add default domain group and use STARTTLS (if no domain there)] *****

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Destination /etc/sssd/sssd.conf does not exist !
", "rc": 257}

```

#### Expected Results:

Skip these tasks if sssd is not installed.

**Comment by jpmahowald** [comment]
One possible fix would be to check for sssd:

```
- name: Is sssd installed
  check_mode: True
  register: package_sssd
  package:
    name: sssd
    state: installed
```

Then default the variable to if it is installed or not. Keeping it in defaults allows the user to override it in their play. 

`sssd_ldap_start_tls: "{{ package_sssd is not changed | default(True) }}"`

**Comment by redhatrises** [comment]
I believe that this issue has been fixed upstream. If not, please open an issue at https://github.com/ComplianceAsCode/content
